workflows:
  android-release:
    name: Android Release

    environment:
      node: 20
      java: 21

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - ~/.pnpm-store

    scripts:
      - pnpm --version
      - pnpm install --frozen-lockfile
      - pnpm run build:release:android

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
