name: Build & Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Environment
        run: |
          pnpm generate:env:release \
            --build-type "Github Action" \
            --node-env production \
            --myanimelist-client-id "${{ vars.MYANIMELIST_CLIENT_ID }}" \
            --anilist-client-id "${{ vars.ANILIST_CLIENT_ID }}"

      - name: Grant execute permission
        run: chmod +x android/gradlew

      - name: Build Release
        run: |
          cd android
          ./gradlew assemblePreRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sora-reader-preRelease
          path: |
            android/**/outputs/**/*.apk
            android/**/outputs/**/*.aab

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ github.run_number }}
          name: Nightly Build ${{ github.run_number }}
          generate_release_notes: true
          files: |
            android/**/outputs/**/*.apk
            android/**/outputs/**/*.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
